// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
// Shane was here
